name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Berjalan setiap hari
  workflow_dispatch: # Bisa dijalankan manual
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Konfigurasi untuk menampilkan repositori privat
          user: username-anda
          template: classic
          base: header, activity, community, repositories
